### ISSUE TITLE
Kailh sockets?

### ISSUE THREAD

**Issue by gwerbin** [dumle29/let-s-Split-v2#3]
I saw on Youtube you were considering making a version of this board that could use the Kailh hotswap sockets. Is that available in this repo?

**Comment by Duckle29** [comment]
Yea it's the V3 and the onboardMCU is kailh. Give it a few weeks and there should be 100 boards for sale at novelkeys :)

**Comment by gwerbin** [comment]
@Duckle29 that's fantastic news. 

Do the Kailh sockets work with the Outemu and BSUN pre-socketed switches? I assume I need to remove the outer socket first, but then will it still fit? As I understand it, the pin inside those sockets is much smaller and rounder than a typical switch pin (which is why you can't use other switches with them).

**Comment by Duckle29** [comment]
I don't think so, but if I were you I'd get a few kailh sockets, and test it. You can get the sockets from novelkeys, I haven't found anyone else who stock them

**Comment by gwerbin** [comment]
@Duckle29 order placed. I'll let you know how it goes.

**Comment by Duckle29** [comment]
@gwerbin Any news on the kailh sockets? Could be cool to know :)

**Comment by gwerbin** [comment]
The sockets seem to work fine. The Outemu (I assume manufactured by Gaote?) pins aren't *that* much smaller.

**Comment by Duckle29** [comment]
Cool. Good to know. I'll close this issue then :)
