### ISSUE TITLE
pads in socket reversible 

### ISSUE THREAD

**Issue by fi0** [dumle29/let-s-Split-v2#4]
https://imgur.com/a/NltYr

Hi - not sure if this is the right place to ask. I'm learning KiCad.
What're the benefits of adding these pads?

thank you :)

**Comment by Duckle29** [comment]
Hello there. No problem :) The layout you are looking at is reverseable, that is, the sockets can be soldered to either side. This means that instead of ordering 20 left halves, and 20 right halves, I can order 40 halves, and get better prices :) The layout is just the normal layout flipped :)

**Comment by fi0** [comment]
thank you :)
