### ISSUE TITLE
onboardMCU branch missing pads

### ISSUE THREAD

**Issue by fi0** [dumle29/let-s-Split-v2#6]
https://imgur.com/a/22Cqy

Pads seems to be missing in the PadsFront layer.

**Comment by Duckle29** [comment]
Which pads? Do you mean for the segger j-link probe? I moved away from that after seeing how expensive the probes are :)

**Comment by Duckle29** [comment]
These ones: https://www.segger.com/products/debug-probes/j-link/accessories/adapters/6-pin-needle-adapter/

**Comment by fi0** [comment]
For the USB port and TRRS, I can see the pads on one side only.

**Comment by Duckle29** [comment]
Oh, you're probably looking at an old branch

**Comment by Duckle29** [comment]
Oh that's the onboard MCU, it's made for cheap production, that means everything is on one side.

**Comment by fi0** [comment]
Should I look into the `lets_split` or `lets_split_panel` in the onboardMCU branch? or both?
